# Generated by Django 3.0.7 on 2020-06-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200605_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
    ]
